name: doctor_admin_panel
description: A doctor admin panel app built with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  animated_text_kit: ^4.2.2
  video_player: ^2.7.0
  chewie: ^1.6.0
  provider: ^6.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - C:\Users\heman\Downloads\doctor_admin_panel\assets\doctor_avatar.png.png
    - C:\Users\heman\Downloads\doctor_admin_panel\assets\logo.png
